AISFormations.Web/Models/ErrorViewModel.cs
using System;

namespace AISFormations.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AISFormations.Web/Models/Formation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AISFormations.Web.Models
{
    public class Formation
    {
        public int Id { get; set; }

        public string Titre { get; set; }

        public string Presentateur { get; set; }

        public string Code { get; set; }

        public string Description { get; set; }

        public string PublicCible { get; set; }

        public DateTime DateHeureDebut { get; set; }

        public double DureeEnHeures { get; set; }

        public int NombrePlacesDisponibles { get; set; }

        public bool EstActive { get; set; }
        
        public List<Participant> Inscriptions { get; set; }

        public Queue<Participant> ListeAttente { get; set; }
    }
}

AISFormations.Web/Models/FormationsContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;


namespace AISFormations.Web.Models
{
    public class FormationsContext : DbContext
    {
        public FormationsContext(DbContextOptions<FormationsContext> options) : base (options) { }

        public DbSet<Formation> Formations { get; set; }

        public DbSet<Participant> Participants { get; set; }
    }
}

AISFormations.Web/Models/Participant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AISFormations.Web.Models
{
    public class Participant
    {
        public int Id { get; set; }

        public string Courriel { get; set; }       
    }
}

AISFormations.Web/Controllers/FormationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AISFormations.Web.Models;
using AISFormations.Web.Services;

namespace AISFormations.Web.Controllers
{
    public class FormationsController : Controller
    {
        private readonly FormationsContext _context;
        private readonly IMessagingService _messagingService;
        
        public FormationsController(FormationsContext context, IMessagingService messagingService)
        {
            _context = context;
            _messagingService = messagingService;
        }

        // GET: Formations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Formations.ToListAsync());
        }

        // GET: Formations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formation == null)
            {
                return NotFound();
            }

            return View(formation);
        }

        // GET: Formations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Formations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titre,Presentateur,Code,Description,PublicCible,DateHeureDebut,DureeEnHeures,NombrePlacesDisponibles,EstActive")] Formation formation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formation);
                await _context.SaveChangesAsync();
                await _messagingService.PushMessage(new FormationMessage() { IdFormation = formation.Id });
                return RedirectToAction(nameof(Index));
            }
            return View(formation);
        }

        // GET: Formations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations.FindAsync(id);
            if (formation == null)
            {
                return NotFound();
            }
            return View(formation);
        }

        // POST: Formations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titre,Presentateur,Code,Description,PublicCible,DateHeureDebut,DureeEnHeures,NombrePlacesDisponibles,EstActive")] Formation formation)
        {
            if (id != formation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormationExists(formation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formation);
        }

        // GET: Formations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var formation = await _context.Formations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formation == null)
            {
                return NotFound();
            }

            return View(formation);
        }

        // POST: Formations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var formation = await _context.Formations.FindAsync(id);
            _context.Formations.Remove(formation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormationExists(int id)
        {
            return _context.Formations.Any(e => e.Id == id);
        }
    }
}

AISFormations.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AISFormations.Web.Models;

namespace AISFormations.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AISFormations.Web/Views/Formations/Create.cshtml
@model AISFormations.Web.Models.Formation

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Formation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presentateur" class="control-label"></label>
                <input asp-for="Presentateur" class="form-control" />
                <span asp-validation-for="Presentateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicCible" class="control-label"></label>
                <input asp-for="PublicCible" class="form-control" />
                <span asp-validation-for="PublicCible" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateHeureDebut" class="control-label"></label>
                <input asp-for="DateHeureDebut" class="form-control" />
                <span asp-validation-for="DateHeureDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DureeEnHeures" class="control-label"></label>
                <input asp-for="DureeEnHeures" class="form-control" />
                <span asp-validation-for="DureeEnHeures" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePlacesDisponibles" class="control-label"></label>
                <input asp-for="NombrePlacesDisponibles" class="form-control" />
                <span asp-validation-for="NombrePlacesDisponibles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="EstActive" /> @Html.DisplayNameFor(model => model.EstActive)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AISFormations.Web/Views/Formations/Delete.cshtml
@model AISFormations.Web.Models.Formation

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Presentateur)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Presentateur)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PublicCible)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublicCible)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateHeureDebut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateHeureDebut)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DureeEnHeures)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DureeEnHeures)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NombrePlacesDisponibles)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NombrePlacesDisponibles)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EstActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstActive)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AISFormations.Web/Views/Formations/Details.cshtml
@model AISFormations.Web.Models.Formation

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Formation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Presentateur)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Presentateur)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PublicCible)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublicCible)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateHeureDebut)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateHeureDebut)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DureeEnHeures)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DureeEnHeures)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NombrePlacesDisponibles)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NombrePlacesDisponibles)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EstActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstActive)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AISFormations.Web/Views/Formations/Edit.cshtml
@model AISFormations.Web.Models.Formation

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Formation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presentateur" class="control-label"></label>
                <input asp-for="Presentateur" class="form-control" />
                <span asp-validation-for="Presentateur" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicCible" class="control-label"></label>
                <input asp-for="PublicCible" class="form-control" />
                <span asp-validation-for="PublicCible" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateHeureDebut" class="control-label"></label>
                <input asp-for="DateHeureDebut" class="form-control" />
                <span asp-validation-for="DateHeureDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DureeEnHeures" class="control-label"></label>
                <input asp-for="DureeEnHeures" class="form-control" />
                <span asp-validation-for="DureeEnHeures" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombrePlacesDisponibles" class="control-label"></label>
                <input asp-for="NombrePlacesDisponibles" class="form-control" />
                <span asp-validation-for="NombrePlacesDisponibles" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="EstActive" /> @Html.DisplayNameFor(model => model.EstActive)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AISFormations.Web/Views/Formations/Index.cshtml
@model IEnumerable<AISFormations.Web.Models.Formation>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Presentateur)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicCible)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateHeureDebut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DureeEnHeures)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombrePlacesDisponibles)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Presentateur)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublicCible)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateHeureDebut)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DureeEnHeures)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombrePlacesDisponibles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstActive)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

AISFormations.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AISFormations.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AISFormations.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

AISFormations.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AISFormations.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AISFormations.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Formations" asp-action="Index">Formations</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AISFormations.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>